EE_CLIENT_ID = '<YOUR_CLIENT_ID_HERE>'
EE_CLIENT_SECRET = "<YOUR_CLIENT_SECRET_HERE>"
EE_REFRESH_TOKEN = "<YOUR_REFRESH_TOKEN_HERE>"
EE_TOKEN_TYPE = 'Bearer'
EE_TOKEN_EXPIRE_IN_SEC = 36000
EE_ACCESS_TOKEN = ''
                                                    
